# Generated by Django 3.1.2 on 2022-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='canditate',
        ),
        migrations.AddField(
            model_name='skills',
            name='canditate',
            field=models.ManyToManyField(null=True, to='api.Candidate'),
        ),
    ]
