# Generated by Django 3.1.2 on 2022-06-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220609_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_hub', models.CharField(max_length=256, verbose_name='github')),
                ('git_flic', models.CharField(max_length=256, verbose_name='gitflic')),
                ('linkedin', models.CharField(max_length=256, verbose_name='linkedIn')),
                ('email', models.EmailField(max_length=100, verbose_name='почта')),
                ('phone_number', models.CharField(default='1234', max_length=17, verbose_name='номер телефона')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
