# Generated by Django 3.1.2 on 2022-06-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_type', models.CharField(default='университет', max_length=256)),
                ('edu_description', models.TextField(verbose_name='описание образования')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
            ],
            options={
                'verbose_name': 'образование',
                'verbose_name_plural': 'образование',
            },
        ),
    ]
