# Generated by Django 3.1.2 on 2022-06-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(default='LMARKT', max_length=200)),
                ('exp_description', models.TextField(verbose_name='описание опыта работы')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
            ],
            options={
                'verbose_name': 'образование',
                'verbose_name_plural': 'образование',
            },
        ),
    ]
