# Generated by Django 3.1.2 on 2022-06-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'опыт работы', 'verbose_name_plural': 'опыт работы'},
        ),
    ]
