# Generated by Django 3.1.2 on 2022-06-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220609_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='canditate',
            field=models.ManyToManyField(default='Дамир Ахмадуллин', to='api.Candidate'),
        ),
    ]
