# Generated by Django 3.1.2 on 2022-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220609_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='canditate',
            field=models.ManyToManyField(null=True, to='api.Candidate'),
        ),
    ]
