# Generated by Django 3.1.2 on 2022-06-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220611_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, null=True, verbose_name='полное имя')),
            ],
            options={
                'verbose_name': 'информация о кандидате',
                'verbose_name_plural': 'информация о кандидате',
            },
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='education',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='canditate',
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(default='университет', max_length=256, verbose_name='тип образования'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(default='LMARKT', max_length=200, verbose_name='название опыта'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.contacts'),
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='education',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.education'),
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='experience',
            field=models.ManyToManyField(to='api.Experience'),
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='skills',
            field=models.ManyToManyField(to='api.Skills'),
        ),
    ]
