# Generated by Django 3.1.2 on 2022-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220611_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='education',
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='education',
            field=models.ManyToManyField(to='api.Education'),
        ),
    ]
