# Generated by Django 3.1.2 on 2022-06-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220611_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='contacts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.contacts'),
        ),
    ]
