# Generated by Django 3.1.2 on 2022-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220611_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='linkedin',
            new_name='vk',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_description',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_icon',
            field=models.TextField(null=True, verbose_name='ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=256, null=True, verbose_name='умения и навыки'),
        ),
    ]
