# Generated by Django 3.1.2 on 2022-06-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220611_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.CharField(max_length=256, verbose_name='vk'),
        ),
    ]
