
name: Portfolio code consistency checkup
  on: 
    push:
      branches: main
    pull_request:
      branches: main
  
  jobs:
    builds:
      runs-on: ubuntu-lates
      
      steps:
      - name: Code checkout
        uses: actions/checkout@v2
        
      - name: Run super-linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}